POST http://localhost:3000/guns
Content-Type: application/json

{
"name": "Pistolet Misia"
}
###
PATCH http://localhost:3000/guns/639727face674272e9edf83f
Content-Type: application/json

{
    "name": "Walther GSP"
}

###

GET http://localhost:3000/guns

###
GET http://localhost:3000/guns/639727f7ce674272e9edf83d
###
DELETE http://localhost:3000/guns/6395fa0bb868fdcf38e029d8
###

POST http://localhost:3000/trainings
Content-Type: application/json

{
    "name": "Misiu trenuje ",
    "date": "12/12/2022"
}

###

PATCH http://localhost:3000/trainings/addGuns
Content-Type: application/json

{
    "gunsToAdd": ["63972c0252eccb2d71c7a1aa"]
    ,
    "id": "63972c1652eccb2d71c7a1af"
}

###

GET http://localhost:3000/trainings

###

GET http://localhost:3000/users

###

GET http://localhost:3000/trainings/639728cb52eccb2d71c7a19d/true

###